import unittest
from domain.company import Company
from domain.bill import Bill
from domain.individual import Individual
from domain.bill_item import BillItem
from domain.currency import Currency
import copy


class TestDomainBill(unittest.TestCase):
    def test_bill_getters_and_setters(self):
        company = Company()
        company.set_company_name("La Geani")
        company.set_registration_number("RO0123")
        company.set_fiscal_no("0000231523647")
        company.set_email_address("la_geani@gmail.com")
        company.set_first_name("Ion")
        company.set_last_name("Bogdan")
        company.set_phone_number("0752314567")
        company.set_fiscal_no("0000012345678")
        company.set_registration_number("RO01923")
        individual = Individual()
        individual.set_cnp("1971209075425")
        individual.set_id(1)
        individual.set_first_name("Petre")
        individual.set_last_name("Vasile")
        individual.set_phone_number("0745321784")
        individual.set_email_address("petre.vasileboss@yahoo.com")
        item = BillItem()
        currency = Currency("$", "Dollar", "USD")
        item.set_id(1)
        item.set_currency(currency)
        item.set_name("McChicken")
        item.set_description("Chicken hamburger")
        item.set_price(2)
        item.set_discount(0)
        bill = Bill()
        bill.set_customer(individual)
        bill.set_currency(currency)
        bill.set_items([item])
        bill.set_id(1)
        bill.set_total(item.get_price())
        bill.set_issuer(company)
        bill.set_issue_date("24.01.2021")
        bill.set_due_date("10.02.2021")
        bill.set_notes("Platiti la Banca Transilvania")
        self.assertEqual(bill.get_currency(), currency)
        self.assertEqual(bill.get_total(), 2)
        self.assertEqual(bill.get_issuer(), company)
        self.assertEqual(bill.get_items(), [item])
        self.assertEqual(bill.get_notes(), "Platiti la Banca Transilvania")
        self.assertEqual(bill.get_issue_date(), "24.01.2021")
        self.assertEqual(bill.get_due_date(), "10.02.2021")
        self.assertEqual(bill.get_customer(), individual)
        bill.add_items(item)
        self.assertEqual(bill.get_items(), [item])

    def test_equal(self):
        company = Company()
        company.set_company_name("La Geani")
        company.set_registration_number("RO0123")
        company.set_fiscal_no("0000231523647")
        company.set_email_address("la_geani@gmail.com")
        company.set_first_name("Ion")
        company.set_last_name("Bogdan")
        company.set_phone_number("0752314567")
        company.set_fiscal_no("0000012345678")
        company.set_registration_number("RO01923")
        individual = Individual()
        individual.set_cnp("1971209075425")
        individual.set_id(1)
        individual.set_first_name("Petre")
        individual.set_last_name("Vasile")
        individual.set_phone_number("0745321784")
        individual.set_email_address("petre.vasileboss@yahoo.com")
        item = BillItem()
        currency = Currency("$", "Dollar", "USD")
        item.set_id(1)
        item.set_currency(currency)
        item.set_name("McChicken")
        item.set_description("Chicken hamburger")
        item.set_price(2)
        item.set_discount(0)
        bill = Bill()
        bill.set_customer(individual)
        bill.set_currency(currency)
        bill.set_items([item])
        bill.set_id(1)
        bill.set_total(item.get_price())
        bill.set_issuer(company)
        bill.set_issue_date("24.01.2021")
        bill.set_due_date("10.02.2021")
        bill.set_notes("Platiti la Banca Transilvania")
        bill2 = copy.deepcopy(bill)
        bill2.set_id(2)
        self.assertNotEqual(bill, bill2)
        bill2.set_id(bill.get_id())
        currency2 = copy.deepcopy(currency)
        currency2.set_name("dollar")
        bill2.set_currency(currency2)
        self.assertNotEqual(bill, bill2)
        bill2.set_currency(bill.get_currency())
        bill2.set_total(12.0)
        self.assertNotEqual(bill, bill2)
        bill2.set_total(bill.get_total())
        bill2.set_notes("asdfg")
        self.assertNotEqual(bill, bill2)
        bill2.set_notes(bill.get_notes())
        bill2.set_items([item, item])
        self.assertNotEqual(bill, bill2)
        bill2.set_items(bill.get_items())
        individual2 = copy.deepcopy(individual)
        individual2.set_cnp("1991212123456")
        bill2.set_customer(individual2)
        self.assertNotEqual(bill, bill2)
        bill2.set_customer(bill.get_customer())
        company2 = copy.deepcopy(company)
        company2.set_last_name("Marcel")
        bill2.set_issuer(company2)
        self.assertNotEqual(bill, bill2)
        bill2.set_issuer(bill.get_issuer())
        bill2.set_due_date("adsf")
        self.assertNotEqual(bill, bill2)
        bill2.set_due_date(bill.get_due_date())
        bill2.set_issue_date("asdf")
        self.assertNotEqual(bill, bill2)

