import unittest
from domain.company import Company
from domain.bill import Bill
from domain.individual import Individual
from domain.bill_item import BillItem
from domain.currency import Currency


class TestDomainBill(unittest.TestCase):
    def test_bill_getters_and_setters(self):
        company = Company()
        company.set_company_name("La Geani")
        company.set_registration_number("RO0123")
        company.set_fiscal_no("0000231523647")
        company.set_email_address("la_geani@gmail.com")
        company.set_first_name("Ion")
        company.set_last_name("Bogdan")
        company.set_phone_number("0752314567")
        company.set_fiscal_no("0000012345678")
        company.set_registration_number("RO01923")
        individual = Individual()
        individual.set_cnp("1971209075425")
        individual.set_id(1)
        individual.set_first_name("Petre")
        individual.set_last_name("Vasile")
        individual.set_phone_number("0745321784")
        individual.set_email_address("petre.vasileboss@yahoo.com")
        item = BillItem()
        currency = Currency("$", "Dollar", "USD")
        item.set_id(1)
        item.set_currency(currency)
        item.set_name("McChicken")
        item.set_description("Chicken hamburger")
        item.set_price(2)
        item.set_discount(0)
        bill = Bill()
        bill.set_customer(individual)
        bill.set_currency(currency)
        bill.set_items([item])
        bill.set_id(1)
        bill.set_tax(item.get_price())
        bill.set_issuer(company)
        bill.set_issue_date("24.01.2021")
        bill.set_due_date("10.02.2021")
        bill.set_notes("Platiti la Banca Transilvania")
        self.assertEqual(bill.get_currency(), currency)
        self.assertEqual(bill.get_tax(), 2)
        self.assertEqual(bill.get_issuer(), company)
        self.assertEqual(bill.get_items(), [item])
        self.assertEqual(bill.get_notes(), "Platiti la Banca Transilvania")
        self.assertEqual(bill.get_issue_date(), "24.01.2021")
        self.assertEqual(bill.get_due_date(), "10.02.2021")
        self.assertEqual(bill.get_customer(), individual)
        bill.add_items(item)
        self.assertEqual(bill.get_items(), [item])
